[2024-10-26 08:58:00,790] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: ETL_task.crawl_data 2024-10-26T00:00:00+00:00 [queued]>
[2024-10-26 08:58:00,802] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: ETL_task.crawl_data 2024-10-26T00:00:00+00:00 [queued]>
[2024-10-26 08:58:00,802] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-10-26 08:58:00,802] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2024-10-26 08:58:00,802] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-10-26 08:58:00,809] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): crawl_data> on 2024-10-26T00:00:00+00:00
[2024-10-26 08:58:00,813] {standard_task_runner.py:52} INFO - Started process 948 to run task
[2024-10-26 08:58:00,817] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ETL_task', 'crawl_data', '2024-10-26T00:00:00+00:00', '--job-id', '7', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmp5yep4i5r', '--error-file', '/tmp/tmpq2kx2wgw']
[2024-10-26 08:58:00,819] {standard_task_runner.py:77} INFO - Job 7: Subtask crawl_data
[2024-10-26 08:58:00,848] {logging_mixin.py:104} INFO - Running <TaskInstance: ETL_task.crawl_data 2024-10-26T00:00:00+00:00 [running]> on host ceff2ee9e0e7
[2024-10-26 08:58:00,880] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=thanhdera@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_task
AIRFLOW_CTX_TASK_ID=crawl_data
AIRFLOW_CTX_EXECUTION_DATE=2024-10-26T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-10-26T00:00:00+00:00
[2024-10-26 08:58:01,196] {logging_mixin.py:104} INFO - Request failed with status code 429
[2024-10-26 08:58:01,197] {python.py:151} INFO - Done. Returned value was: None
[2024-10-26 08:58:01,207] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=ETL_task, task_id=crawl_data, execution_date=20241026T000000, start_date=20241026T085800, end_date=20241026T085801
[2024-10-26 08:58:01,228] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-26 08:58:01,270] {local_task_job.py:149} INFO - Task exited with return code 0
